apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-scheduler-check.fullname" . }}
  labels:
    {{- include "gpu-scheduler-check.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "gpu-scheduler-check.selectorLabels" . | nindent 4 }}