apiVersion: v1
kind: Secret
metadata:
  name: local-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: gpu-enabled
data:
  name: bG9jYWwtY2x1c3Rlcg==  # base64 encoded "local-cluster"
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj  # base64 encoded "https://kubernetes.default.svc"
type: Opaque 