apiVersion: v2
name: gpu-scheduler
description: A Helm chart for the GPU Scheduler - Custom Kubernetes scheduler for GPU device assignment
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - scheduler
  - gpu
  - cuda
home: https://gitlab.com/evgenii19/gpu-scheduler
maintainers:
  - name: GPU Scheduler Team
    email: team@example.com
