{{- if .Values.webhook.caBundle }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "gpu-scheduler.fullname" . }}-webhook
  labels:
    {{- include "gpu-scheduler.labels" . | nindent 4 }}
webhooks:
  - name: gpu-env-injector.gpu-scheduler.io
    clientConfig:
      service:
        name: {{ include "gpu-scheduler.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: {{ .Values.webhook.caBundle }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - kube-system
            - kube-public
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
{{- end }} 