{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-scheduler.fullname" . }}-webhook
  labels:
    {{- include "gpu-scheduler.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "gpu-scheduler.selectorLabels" . | nindent 4 }}
{{- end }} 